version: '2'
services:
  nginx:
    image: "${APP_NAME}-nginx:${TAG}"
    restart: always
    depends_on:
      - php
    links:
      - php
  php:
    restart: always
    links:
      - db:db
    depends_on:
      - db
  db:
    image: "${APP_NAME}-db:${TAG}"
    restart: always