version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: "./docker/source/nginx/dev/Dockerfile"
    volumes:
      - "./app/okocrm:/app"
      - "./docker/source/nginx/dev/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/dev:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "${EXTERNAL_WEB_DEV_PORT}:80"
    env_file:
      - "./docker/env/dev/VIRTUAL_HOST.env"
      - "./docker/env/dev/APP_ENV.env"
  db:
    build:
      context: ./
      dockerfile: "./docker/source/mysql/dev/Dockerfile"
    ports:
      - "${EXTERNAL_DB_DEV_PORT}:33065"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/source/mysql/db_dump/db_okocrm:/docker-entrypoint-initdb.d"
      - "./docker/source/mysql/tmp:/var/tmp"
    env_file:
      - "./docker/env/dev/db.env"
  php:
    image: "${APP_NAME}-php-dev:${TAG}"
    build:
      context: ./
      dockerfile: "./docker/source/php/dev/Dockerfile"
    volumes:
      - "./app/okocrm:/app"
    env_file:
      - "./docker/env/dev/XDEBUG_CONFIG.env"
      - "./docker/env/dev/PHP_IDE_CONFIG.env"
      - "./docker/env/dev/APP_ENV.env"
volumes:
  db_data:
    external: false
